Fix/directors grid
poulami-saha/Global-Code-Queens-MyTeam-Website pull request #41
Opened 2024-07-31 14:08 UTC by FevenSeyfu

Refactor the about page > Directors card to use grid, changes include

- updated layout's inline padding unit to % to resize on smaller screens
- change the Directors Profile card to Grid
- made changes to the quote container padding and margins to use relative units

2024-07-31 21:23 UTC, joanwolk commented
I think https://github.com/poulami-saha/Global-Code-Queens-MyTeam-Website/pull/41/commits/224978bae87c4cdfc70d6275bcecedc90104c147 might need to be reversed, because proportional padding does stuff like this (680px-767px, wide end of mobile width; the text pushes much too far down the card and the social links get hidden). 
<img width="754" alt="Screenshot 2024-07-31 at 2 15 22 PM" src="https://github.com/user-attachments/assets/47bdaf03-9bf3-4974-97c8-d3f65866b690">

A similar thing can happen at very narrow desktop sizes:
<img width="967" alt="Screenshot 2024-07-31 at 2 18 19 PM" src="https://github.com/user-attachments/assets/ff398d76-4e5d-47e3-9401-5a6bb1530695">

2024-07-31 23:18 UTC, joanwolk commented
Using the original padding has its own problems, I see. I'm working on an alternative that uses grid for the profile cards, but I'm going to have to either (1) do something a little hacky with the display to make the card size stretch vertically based on the quote while displaying the avatar, or (2) animate a transition of some kind to account for the card rendering bigger on the quote side. 

Alternative solutions:
- we leave the directors section as it was, which will, in fact, be 3 columns wide at 1440px and above
- we leave it as it was, BUT add some negative margins to the `.profiles` div so it gets up to 3 columns sooner. How weird this looks will depend on how much vertical space the user has to be able to see the profile cards extend past the header/footer edges; example below with `margin-inline: -60px;` at viewport width of 1322. It's noticeable but maybe ok?
<img width="1322" alt="Screenshot 2024-07-31 at 4 16 58 PM" src="https://github.com/user-attachments/assets/11d2a9f5-59d7-49a5-a446-3a980c999697">

2024-08-01 00:06 UTC, FevenSeyfu commented
Hi @joanwolk  as suggested I have reverted the changes to make the padding relative.I see the options you have listed and the issue I had with making the cards vertically responsive was the layout of the cards and the buttons being aligned relative to the card with out a fixed height for the cards it miss alignes it for Quote vs the avatar containers.                      
As an alternative review my latest commit  not an ideal solutions but considering the time keeping the inline padding relative and moving the breaking point for the desktop from 960px to 1250 or even 1440px for the  grid it should keep both quotes and avatar cards correctly aligned.

2024-08-01 01:37 UTC, eunicey reviewed
From what I'm understanding, with larger desktops we either lose the 3x2 structure of the cards (if we keep it as it was) or the button overlaps with the social links (with the latest commit). I would rather lose the structure than have the content overlap, IMO.

2024-08-01 03:13 UTC, joanwolk commented
> * our other option is keeping it as is, the issue I have is with the flex-wrap for bigger desktops it keeps wrapping cards which causes it to lose form we can also limit that in some way

This is easily fixed by giving a max-width to the `.profiles` div so it can't get wider than the 3-column layout

2024-08-01 09:28 UTC, poulami-saha commented on src/components/AboutContainer/Directors/Directors.module.css
> +@media (min-width: 1250px) {
I think we are getting deviated a bit from the requirement now, we finalized only 2 media breakpoints 768 and 960, I believe for the rest of the application 1250 is not being considered

2024-08-01 16:23 UTC, FevenSeyfu commented on src/components/AboutContainer/Directors/Directors.module.css
> +@media (min-width: 1250px) {
Yes that is why I have mentioned it is not and ideal solution considering the time I can't redo the profileCards to be vertically responsive in time if anyone else can feel free to do so, as suggested we can leave it as is and  close the PR  @eunicey  can you redo your changes in separate PR or revert the UI changes and merge it in this PR.

2024-08-01 17:28 UTC, eunicey commented on src/components/AboutContainer/Directors/Directors.module.css
> +@media (min-width: 1250px) {
@FevenSeyfu - I don't know what the final consensus is on the UI changes here so I'll leave this PR alone and make a separate PR for the testing scripts.

2024-08-01 21:09 UTC, joanwolk requested changes
Please review #45 and if that resolves the issue well enough, that one can be accepted and this can be closed WITHOUT merging.

2024-08-02 02:38 UTC, closed without merging