add info about using git in a group
poulami-saha/Global-Code-Queens-MyTeam-Website pull request #6
Opened 2024-06-23 08:21 UTC by joanwolk

I've added some info to `README.md` and some is better than none, but it's very possible that I missed some points that should be added. 

Feel free to comment with questions we should address or anything else that comes to mind!

2024-06-23 13:27 UTC, FevenSeyfu approved these changes
Hi @joanwolk great instructions you have written. I am sure it will come in hand for most of us.
<img src="https://media1.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif"/>
 My only suggestion is
- include commands to install and start the app, after cloning and navigating to local copy
-  if you could add tips to  prevent  conflict to begin with as it can be a rabbit hole specially for a beginner

2024-06-23 21:44 UTC, poulami-saha commented on README.md
> +    - Merge the current state of any branch(es) that you want features from
```suggestion
    - Merge the current state of any branch(es) that you want features from using
    `git pull origin desired-branch-name`
```

2024-06-24 16:21 UTC, poulami-saha requested changes

2024-06-24 16:21 UTC, poulami-saha commented on README.md
> +- PRs must be approved by at least one team member before they are merged.
```suggestion
- PRs must be approved by at least one team member before they are merged.
-Please do not merge your PR if you have 1 approval and there is a change requested by another approver. Please address all comments before merging the PR.
```

2024-06-24 16:21 UTC, poulami-saha commented on README.md
> +    ```
```suggestion
    ```
    3. Currently please use npm package manager and not yarn for this project.
```

2024-06-24 18:59 UTC, joanwolk commented on README.md
> +    ```
Good note. Added the following as a more detailed breakdown of getting started and using npm:

```
4. This project uses npm as its package manager (not yarn). Install the dependencies by running `npm install`.
5. Start the local dev server with `npm start`.
  - If you haven't run `npm install`, you won't be able to start the site.
  - Occasionally, new dependencies may be added. When this happens, you'll probably need to run the install command again.
```

2024-06-24 19:00 UTC, joanwolk commented on README.md
> +- PRs must be approved by at least one team member before they are merged.
Added, with markdown formatting corrected 👍

2024-06-25 05:15 UTC, poulami-saha approved these changes

2024-06-25 05:15 UTC, merged